### ISSUE TITLE
usePositionStream not refreshing algo orders with current refresh function

### ISSUE THREAD

**Issue by Veenoway** [OrderlyNetwork/js-sdk#3]
ISSUE:

Actually the usePositionStream got a refresh function that will refresh the fetch "/v1/positions".

It isn't refreshing the useOrderStream included in the usePositionStream hook.

This will lead to an issue after a long inactivity on the app, algo orders won't be retrigger so it will show current position but algo orders won't be return updated if the user add a new TP SL. 

FIX:
Adding a custom function who will execute refresh function from useOrderStream & refresh function from "/v1/positions".

**Comment by Tarnadas** [comment]
Thx for this issue and fix!

It is eligible worth **100 points** for Dev Maxi role:
https://github.com/OrderlyNetwork/Dev-Maxi/issues/3

I will close this, but the commit will be added to our repo once merged on Gitlab
